repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-ast
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: detect-private-key
    - id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
