"""
Matmul-of-Experts (MoE) with Outer-Gather-Scatter (OGS)
"""


from __future__ import annotations

import torch
import triton
import triton.language as tl

@triton.jit
def __moe_matmul_ogs_maxT_kernel(expert_token_offsets, expert_token_counts, row_ids, sorted_to_orig_token_idx, k_ids, A, W, C, A_stride_0, A_stride_1, C_stride_0, C_stride_1, W_stride_0, W_stride_1, W_stride_2, expert_token_counts_stride_0, expert_token_offsets_stride_0, k_ids_stride_0, row_ids_stride_0, sorted_to_orig_token_idx_stride_0, N, T_max, K, _BLOCK_SIZE_2: tl.constexpr, _BLOCK_SIZE_1: tl.constexpr, _BLOCK_SIZE_3: tl.constexpr):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    start = tl.load(expert_token_offsets + indices_0 * expert_token_offsets_stride_0, None)
    num_tokens = tl.load(expert_token_counts + indices_0 * expert_token_counts_stride_0, None)
    v_0 = tl.full([], 0, tl.int32)
    v_1 = num_tokens != v_0
    if v_1:
        num_tokens_copy = num_tokens
        start_copy = start
        for offset_1 in range(0, T_max, _BLOCK_SIZE_1):
            indices_1 = offset_1 + tl.arange(0, _BLOCK_SIZE_1).to(tl.int32)
            mask_1 = indices_1 < T_max
            for offset_2 in range(0, N, _BLOCK_SIZE_2):
                indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
                mask_2 = indices_2 < N
                num_tokens_copy_copy = num_tokens_copy
                start_copy_copy = start_copy
                load = tl.load(row_ids + indices_1 * row_ids_stride_0, mask_1, other=0)
                squeeze = tl.reshape(load, [_BLOCK_SIZE_1])
                local_rows = tl.reshape(squeeze, [_BLOCK_SIZE_1])
                v_2 = num_tokens_copy_copy[None]
                v_3 = local_rows < v_2
                squeeze_2 = tl.reshape(v_3, [_BLOCK_SIZE_1])
                row_valid = tl.reshape(squeeze_2, [_BLOCK_SIZE_1])
                v_4 = tl.full([], 1, tl.int32)
                v_5 = num_tokens_copy_copy - v_4
                v_6 = v_5[None]
                v_7 = tl.where(row_valid, local_rows, v_6)
                v_8 = start_copy_copy[None]
                v_9 = v_8 + v_7
                squeeze_4 = tl.reshape(v_9, [_BLOCK_SIZE_1])
                orig_rows = tl.load(sorted_to_orig_token_idx + squeeze_4 * sorted_to_orig_token_idx_stride_0, mask_1, other=0)
                acc = tl.full([_BLOCK_SIZE_1, _BLOCK_SIZE_2], 0.0, tl.float32)
                for offset_3 in range(0, K, _BLOCK_SIZE_3):
                    indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3).to(tl.int32)
                    mask_3 = indices_3 < K
                    row_valid_copy = row_valid
                    orig_rows_copy = orig_rows
                    acc_copy = acc
                    load_1 = tl.load(k_ids + indices_3 * k_ids_stride_0, mask_3, other=0)
                    col_ids = tl.reshape(load_1, [_BLOCK_SIZE_3])
                    v_10 = K.to(tl.int32)
                    v_11 = col_ids < v_10
                    subscript = row_valid_copy[:, None]
                    subscript_1 = v_11[None, :]
                    v_12 = subscript & subscript_1
                    v_13 = v_12 == 0
                    subscript_2 = orig_rows_copy[:, None]
                    squeeze_1 = tl.reshape(subscript_2, [_BLOCK_SIZE_1])
                    load_2 = tl.load(A + (squeeze_1[:, None] * A_stride_0 + indices_3[None, :] * A_stride_1), mask_1[:, None] & mask_3[None, :], other=0)
                    v_14 = tl.full([], 0.0, tl.float16)
                    v_15 = v_14[None, None]
                    v_16 = tl.where(v_13, v_15, load_2)
                    A_frag = tl.reshape(v_16, [_BLOCK_SIZE_1, _BLOCK_SIZE_3])
                    W_frag = tl.load(W + (indices_0[:, None] * W_stride_0 + indices_3[:, None] * W_stride_1 + indices_2[None, :] * W_stride_2), mask_3[:, None] & mask_2[None, :], other=0)
                    acc = tl.dot(A_frag, W_frag, acc=acc_copy, input_precision='tf32')
                view = tl.reshape(row_valid, [_BLOCK_SIZE_1, 1])
                valid_store_mask = tl.broadcast_to(view, [_BLOCK_SIZE_1, _BLOCK_SIZE_2])
                
                # v1 (generated by Helion, numerically off)
                C_tile = tl.load(
                    C + (orig_rows[:, None] * C_stride_0 + indices_2[None, :] * C_stride_1),
                    mask_1[:, None] & mask_2[None, :],
                    other=0
                )
                v_19 = tl.where(valid_store_mask, acc, C_tile.to(tl.float32))
                tl.store(
                    C + (orig_rows[:, None] * C_stride_0 + indices_2[None, :] * C_stride_1),
                    v_19.to(tl.float16),
                    mask = mask_1[:, None] & mask_2[None, :]  # & valid_store_mask  # adding this make it correct
                )

                # v2 (custom Triton, numerically correct)
                # tl.store(
                #     C + (orig_rows[:, None] * C_stride_0 + indices_2[None, :] * C_stride_1),
                #     acc.to(tl.float16),
                #     mask = mask_1[:, None] & mask_2[None, :] & valid_store_mask
                # )

def _moe_matmul_ogs_maxT(A: torch.Tensor, W: torch.Tensor, expert_token_counts: torch.Tensor, expert_token_offsets: torch.Tensor, sorted_to_orig_token_idx: torch.Tensor, T_max_tensor: torch.Tensor):
    B, K = A.shape
    E, _, N = W.shape
    T_max = T_max_tensor.numel()
    C = torch.empty(B, N, dtype=torch.promote_types(A.dtype, W.dtype), device=A.device)
    row_ids = torch.arange(T_max, device=A.device, dtype=torch.int32)
    k_ids = torch.arange(K, device=A.device, dtype=torch.int32)
    _BLOCK_SIZE_2 = 16
    _BLOCK_SIZE_1 = 16
    _BLOCK_SIZE_3 = 16
    __moe_matmul_ogs_maxT_kernel[E,](expert_token_offsets, expert_token_counts, row_ids, sorted_to_orig_token_idx, k_ids, A, W, C, A.stride(0), A.stride(1), C.stride(0), C.stride(1), W.stride(0), W.stride(1), W.stride(2), expert_token_counts.stride(0), expert_token_offsets.stride(0), k_ids.stride(0), row_ids.stride(0), sorted_to_orig_token_idx.stride(0), N, T_max, K, _BLOCK_SIZE_2, _BLOCK_SIZE_1, _BLOCK_SIZE_3, num_warps=4, num_stages=3)
    return C


def moe_matmul_ogs(
    A: torch.Tensor,  # [B, K]
    W: torch.Tensor,  # [E, K, N]
    top1_expert_per_token: torch.Tensor,  # [B]
    variant: str,
) -> torch.Tensor:
    """Top-level helper that prepares the dispatch metadata and launches the
    Helion kernel.

    Parameters
    ----------
    A : Tensor[ B, K ]
        Input activations (one row per token).
    W : Tensor[ E, K, N ]
        Expert weight matrices.
    top1_expert_per_token : Tensor[ B ] (int32 / int64)
        Routing decisions - *which* expert each token is sent to.
    variant : str
        Variant of the OGS kernel to use.
        - "raggedT" : ragged-T variant
        - "maxT" : max-T variant
    """

    assert variant in ["raggedT", "maxT"]

    B = A.size(0)
    E = W.size(0)
    device = A.device

    sorting = torch.argsort(top1_expert_per_token, stable=True).to(torch.int32)  # [B]
    expert_token_counts = torch.bincount(
        top1_expert_per_token, minlength=E
    ).to(torch.int32)  # [E]

    expert_token_offsets = torch.empty(E + 1, dtype=torch.int32, device=device)  # [E+1]
    expert_token_offsets[0] = 0
    expert_token_offsets[1:] = torch.cumsum(expert_token_counts, 0, dtype=torch.int32)

    if variant == "maxT":
        T_max = int(expert_token_counts.max().item())
        C = _moe_matmul_ogs_maxT(
            A,
            W,
            expert_token_counts,
            expert_token_offsets,
            sorting,
            torch.empty(T_max, device=device),
        )
    # elif variant == "raggedT":
    #     C = _moe_matmul_ogs_raggedT(
    #         A,
    #         W,
    #         expert_token_counts,
    #         expert_token_offsets,
    #         sorting,
    #     )

    return C


def moe_ref(A: torch.Tensor, W: torch.Tensor, top1_expert_per_token: torch.Tensor) -> torch.Tensor:
    B, K = A.shape
    N = W.size(2)
    device, dtype = A.device, torch.promote_types(A.dtype, W.dtype)

    C = torch.empty(B, N, device=device, dtype=dtype)
    n_experts = W.size(0)

    for e in range(n_experts):
        token_idx = (top1_expert_per_token == e).nonzero(as_tuple=True)[0]
        if token_idx.numel() == 0:
            continue
        C[token_idx] = A[token_idx] @ W[e]  # [Ne, K] @ [K, N]

    return C


def check() -> None:
    from triton.testing import do_bench

    B = 128   # tokens / rows
    K = 64    # hidden size
    N = 32    # output size
    n_experts = 32
    dtype = torch.float16

    device = "cuda" if torch.cuda.is_available() else "cpu"

    top1_expert_per_token = torch.randint(n_experts, (B,), device=device)
    A = torch.randn(B, K, device=device, dtype=dtype)
    W = torch.randn(n_experts, K, N, device=device, dtype=dtype)

    def _check_variant(variant: str) -> None:
        C_helion = moe_matmul_ogs(A, W, top1_expert_per_token, variant)
        C_ref = moe_ref(A, W, top1_expert_per_token)
        torch.testing.assert_close(C_helion, C_ref, atol=1e-2, rtol=1e-2)

        sec = do_bench(lambda: moe_matmul_ogs(A, W, top1_expert_per_token, variant))
        baseline_sec = do_bench(lambda: moe_ref(A, W, top1_expert_per_token))
        print(f"Helion time: {sec:.4f}s, torch time: {baseline_sec:.4f}s, speed-up: {baseline_sec/sec:.2f}x")

    # _check_variant("raggedT")
    _check_variant("maxT")


if __name__ == "__main__":
    check()
