name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-cuda12.6-py${{ matrix.python-version }}-a10g

    container:
      image: pytorch/almalinux-builder:cuda12.6
      options: --gpus all

    runs-on: linux.g5.4xlarge.nvidia.gpu

    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: torch27
          python-version: ${{ matrix.python-version }}
          channels: defaults,pytorch,conda-forge

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.conda/pkgs
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ matrix.python-version }}-${{ hashFiles('.github/workflows/test.yml', 'requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install CUDA
        run: |
          conda install nvidia/label/cuda-12.6.3::cuda-toolkit

      - name: Install PyTorch
        run: |
          pip3 install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu126

      - name: Install Triton
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./.github/scripts/install_triton.sh

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s test/ -p "*.py" -v -t .
