name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test-template.yml
    with:
      test-name: test
      ref-eager: false

  test-ref-eager:
    uses: ./.github/workflows/test-template.yml
    with:
      test-name: test-ref-eager
      ref-eager: true
