name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-cuda12.6-py${{ matrix.python-version }}-a10g

    container:
      image: nvidia/cuda:12.6.3-devel-ubuntu24.04
      options: --gpus all

    runs-on: linux.g5.4xlarge.nvidia.gpu

    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: torch27
          python-version: ${{ matrix.python-version }}
          channels: defaults,pytorch,conda-forge

      - name: Get current month
        id: date
        run: echo "month=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.conda/pkgs
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ matrix.python-version }}-${{ hashFiles('.github/workflows/test.yml', 'requirements.txt') }}-${{ steps.date.outputs.month }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install PyTorch
        run: |
          pip3 install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cu126

      - name: Install Triton
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          apt-get update
          apt-get install -y git
          mkdir -p /tmp/$USER
          cd /tmp/$USER
          pip uninstall -y triton pytorch-triton || true
          rm -rf triton/ || true
          git clone https://github.com/triton-lang/triton.git
          cd triton/
          conda install -y -c conda-forge gcc_linux-64=13 gxx_linux-64=13 gcc=13 gxx=13
          pip install -r python/requirements.txt
          MAX_JOBS=$(nproc) TRITON_PARALLEL_LINK_JOBS=2 pip install .
          cd /tmp/$USER
          rm -rf triton/

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover -s test/ -p "*.py" -v -t .
